### ISSUE TITLE
[Page: Editor] Dark Mode for the Editor seems to be broken!

### ISSUE THREAD

**Issue by ProProgrammer2504** [exercism/v3-beta#24] opened 2021-05-21 16:28 UTC
![2021-05-21 (1)](https://user-images.githubusercontent.com/73734376/119168998-25a33d00-ba7f-11eb-88bb-8c154554aea0.png)

I was checking the Dark Mode of the Editor and it seems to turn a single line in dark mode.
When I shift to different lines, the line selected changes into dark mode.

**Comment by iHiD** [comment] 2021-05-21 21:28
Thanks for opening. Duplicate of https://github.com/exercism/v3-beta/issues/6

**Closed by iHiD** 2021-05-21 21:28 UTC
Labels: status/duplicate
