### ISSUE TITLE
[Track] Link Handles in Track Activity to Profiles

### ISSUE THREAD

**Issue by taiyab** [exercism/v3-beta#282] opened 2021-08-27 11:14 UTC
![image](https://user-images.githubusercontent.com/5337876/131119240-b3acd5a0-89b1-4211-91fb-694314cabe2d.png)

The handles should link to their respective profiles.

**Comment by iHiD** [comment] 2021-08-29 01:23
Duplicate of https://github.com/exercism/v3-beta/issues/240

**Closed by iHiD** 2021-08-29 01:23 UTC
Labels: blocking/no
