### ISSUE TITLE
[Contributing/Contributors] Last 7 days contributors are not sorted by reputation

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3-beta#63] opened 2021-06-20 11:47 UTC
I understand that the data about contributions is not yet fully correct, but I'm not sure if that is the cause of this bug. When I browse contributors from the last 7 days, they seem in random order. In any other period (last 30 days, last year, all time) they're ordered by reputation.

<img width="1392" alt="Screen Shot 2021-06-20 at 13 40 42" src="https://user-images.githubusercontent.com/7852553/122672859-f3941080-d1cd-11eb-86b9-75d99cb5e134.png">

<img width="1392" alt="Screen Shot 2021-06-20 at 13 42 05" src="https://user-images.githubusercontent.com/7852553/122672856-f0008980-d1cd-11eb-9fba-a4344e469954.png">

**Comment by angelikatyborska** [comment] 2021-06-20 11:53
OK, maybe it's not true that the sorting is always correct for periods other than 7 days. If I filter it to just the C track, it is wrong for both 7 days and 30 days.

<img width="1392" alt="Screen Shot 2021-06-20 at 13 51 58" src="https://user-images.githubusercontent.com/7852553/122673020-dc095780-d1ce-11eb-8cd1-674f00f0249c.png">

<img width="1392" alt="Screen Shot 2021-06-20 at 13 52 02" src="https://user-images.githubusercontent.com/7852553/122673017-da3f9400-d1ce-11eb-9275-37d4e42afef0.png">

**Comment by iHiD** [comment] 2021-06-23 11:48
The issue is actually that half those people shouldn't actually be on here because my marking login (in the mark and sweep that powers this) was very wrong.

**Comment by iHiD** [comment] 2021-06-23 11:48
(Fixed in https://github.com/exercism/website/pull/1151)

**Closed** 2021-06-23 23:30 UTC
Labels: status/fixed-pending-deploy

**Comment by angelikatyborska** [comment] 2021-07-03 15:12
@iHiD As I was browsing the end of the all time contributors, I noticed a single entry being out of place. There's a 0 reputation person in there. On some tracks, you also show up with a 0 that's out of order (Bash, C#, Clojure, Dart, Elm...)

<img width="1191" alt="Screen Shot 2021-07-03 at 17 06 27" src="https://user-images.githubusercontent.com/7852553/124358718-d3c70880-dc21-11eb-8e8a-ea0599a3be0a.png">

<img width="1191" alt="Screen Shot 2021-07-03 at 17 08 30" src="https://user-images.githubusercontent.com/7852553/124358733-e5a8ab80-dc21-11eb-8825-ecac75651cdd.png">

**Comment by iHiD** [comment] 2021-07-03 16:56
Ah! This will be people who have deleted/reset their accounts. I'll open a new issue. Thanks :)
