### ISSUE TITLE
[Page iterations] : Syntax highlighting seems broken on some exercises' iterations

### ISSUE THREAD

**Issue by TomPradat** [exercism/v3-beta#41] opened 2021-05-31 20:37 UTC
![syntax-highlighting-pbm](https://user-images.githubusercontent.com/16164512/120240226-5560fa80-c260-11eb-9952-e64da8b4df49.jpg)

Let me know if you need more information

**Comment by iHiD** [comment] 2021-05-31 21:26
Hi. Thanks for the report. What language is this?

**Comment by TomPradat** [comment] 2021-05-31 21:39
This is Javascript 👍

Le lun. 31 mai 2021 à 23:26, Jeremy Walker ***@***.***> a
écrit :

**Comment by iHiD** [comment] 2021-05-31 23:13
Thanks. Would you mind pasting the actual code in here so I can try and reproduce pls! :)

**Comment by iHiD** [comment] 2021-06-01 00:24
(cc @joshgoebel too in case it's obvious to you)

**Comment by iHiD** [comment] 2021-06-01 00:25
(Btw, at a glance it looks like you might not be closing a string before we get to this bit of the code - either a mistake in your code or a mistake in some part of the highlighter)

**Comment by TomPradat** [comment] 2021-06-01 08:10
Here is the code :

```javascript
//
// This is only a SKELETON file for the 'Kindergarten Garden' exercise.
// It's been provided as a convenience to get you started writing code faster.
//

const DEFAULT_STUDENTS = [
  'Alice',
  'Bob',
  'Charlie',
  'David',
  'Eve',
  'Fred',
  'Ginny',
  'Harriet',
  'Ileana',
  'Joseph',
  'Kincaid',
  'Larry',
];

const PLANT_CODES = {
  G: 'grass',
  V: 'violets',
  R: 'radishes',
  C: 'clover',
};

export class Garden {
  constructor(diagram, students = DEFAULT_STUDENTS) {
    this.diagram = diagram;
    this.students = students.sort();
  }

  plants(student) {
    const [firstRow, secondRow] = this.diagram.split("\n");
		const studentIndex = this.students.indexOf(student);
    const plantsColumnIndex = studentIndex * 2;

    const plantsOfTheFirstRowOwnedByTheStudent = firstRow.slice(plantsColumnIndex, plantsColumnIndex + 2);
    const plantsOfTheSecondRowOwnedByTheStudent = secondRow.slice(plantsColumnIndex, plantsColumnIndex + 2);

    return [...plantsOfTheFirstRowOwnedByTheStudent, ...plantsOfTheSecondRowOwnedByTheStudent].map(plantCode => PLANT_CODES[plantCode]);
  }
}

```

It works well when I'm in the editor btw

**Comment by joshgoebel** [comment] 2021-06-01 08:27
Too bad the snap is missing lines 1-13... I'd imagine there is a syntax error and a missing quote...

**Comment by TomPradat** [comment] 2021-06-01 09:51
@joshgoebel Here it is :)

![Exercism](https://user-images.githubusercontent.com/16164512/120303903-92b0a100-c2cf-11eb-970f-c6b4219412ce.jpg)

**Comment by joshgoebel** [comment] 2021-06-01 09:56
It looks like it's _not_ getting highlighted as JS but rather some other language, which would be an Exercism bug?  Are we not passing the languages explicitly?  We definitely should be.

**Comment by iHiD** [comment] 2021-06-01 11:20
Hmm, yeah. This is a bug our end. The wrong language is getting set. I'll take a look.

**Comment by iHiD** [comment] 2021-06-01 11:36
Fixed in https://github.com/exercism/website/pull/1049 :)

**Closed** 2021-06-01 12:20 UTC
Labels: status/fixed-pending-deploy
