### ISSUE TITLE
Authors on feed look clickable, but don't do anything

### ISSUE THREAD

**Issue by kntsoriano** [exercism/v3-beta#266] opened 2021-08-26 05:37 UTC
![Screen Shot 2021-08-26 at 1 36 54 PM](https://user-images.githubusercontent.com/1901520/130906837-407aa5c2-e52d-4a25-a050-1d70c196116b.png)

**Comment by iHiD** [comment] 2021-08-29 01:22
Duplicate of https://github.com/exercism/v3-beta/issues/240

**Closed by iHiD** 2021-08-29 01:22 UTC
Labels: blocking/no
